[tool.black]
line-length = 80

[tool.pytest.ini_options]
log_cli = "true"
log_cli_level = "info"
log_file_level = "debug"
log_cli_format ="%(asctime)-15s [%(levelname)-8s] [%(funcName)-40s]  %(message)s"
log_file_format = "%(asctime)-15s [%(levelname)-8s] [%(funcName)-40s]  %(message)s"
log_cli_date_format = "%Y-%m-%dT%H:%M:%S%z"
log_file_date_format = "%Y-%m-%dT%H:%M:%S%z"
markers = [
    "owner: Test function owner, used for Azure DevOps assignment", 
    "area: Test function product area path, used for Azure DevOps assignment",
]
filterwarnings = [
    "ignore::pytest.PytestExperimentalApiWarning",
]